drop table if exists cat cascade;
CREATE TABLE cat (
    id BIGINT GENERATED BY DEFAULT AS identity,
    evil BOOLEAN NOT NULL,
    has_whiskers BOOLEAN NOT NULL,
    length INTEGER NOT NULL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);